//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEligible
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_Trials
    {
        public string nci_id { get; set; }
        public string nct_id { get; set; }
        public string id { get; set; }
        public string inclusion_indicaInclusionor { get; set; }
        public string description { get; set; }
    }
}
