version: '2'

services:
  flask:
    restart: always
    build:
      context: .
      dockerfile: compose/flask/Dockerfile
    volumes:
      - .:/ct_eligible
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.2
    ports:
      - "27017:27017"
